NetNua/logs/urls.py
from django.urls import path
from . import views

app_name = 'logs'

urlpatterns = [
    path('', views.log_list, name='log_list'),
]

NetNua/logs/models.py
from django.db import models
from upgrades.models import UpgradeEvent
from script_manager.models import Script
from devices.models import Device


class Log(models.Model):
    TYPE_CHOICES = (
        ('upgrade', 'Upgrade'),
        ('script', 'Script'),
    )

    log_type = models.CharField(max_length=10, choices=TYPE_CHOICES)
    message = models.TextField()
    device = models.ForeignKey(Device, null=True, blank=True, on_delete=models.CASCADE)
    upgrade = models.ForeignKey(UpgradeEvent, null=True, blank=True, on_delete=models.CASCADE)
    script = models.ForeignKey(Script, null=True, blank=True, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey('auth.User', null=True, blank=True, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.log_type} - {self.timestamp}"

NetNua/logs/views.py
from django.shortcuts import render
from devices.models import Device
from script_manager.models import Script
from upgrades.models import UpgradeEvent
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Log

@login_required
def log_list(request):
    logs = Log.objects.all().order_by('-timestamp')
    context = {
        'logs': logs,
    }
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['logs'] = Log.objects.all()
        context['device'] = Device.objects.all()
        context['script'] = Script.objects.all()
        context['upgrade'] = UpgradeEvent.objects.all()
        return context

    return render(request, 'logs/log_list.html', context)

NetNua/logs/templates/logs/log_list.html
{% extends 'devices/base.html' %}

{% block content %}
  <h2>Logs</h2>
  <table class = "table tabled-bordered table-hover">
    <thead>
      <tr>
        <th>Type</th>
        <th>Instance</th>
        <th>Message</th>
        <th>Timestamp</th>
        <th>User</th>

      </tr>
    </thead>
    <tbody>
      {% for log in logs %}
        <tr>
          <td>{{ log.get_log_type_display }}</td>
          {% if log.device %}
          <td>Device: {{ log.device.dnsName }}</td>
          {% endif %}
          {% if log.script %}
            <td>Log: {{ log.script.name }}</td>
            {% endif %}
            {% if log.upgrade %}
              <td>Upgrade: {{ log.upgrade.name }}</td>
              {% endif %}
          <td>{{ log.message }}</td>
          <td>{{ log.timestamp }}</td>
          <td>{{ log.user.username}}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="3">No logs found.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}