NetNua/logs/urls.py
from django.urls import path
from . import views

app_name = 'logs'

urlpatterns = [
    path('', views.log_list, name='log_list'),
]

NetNua/upgrades/urls.py
from django.urls import path
from .views import UpgradeListView, UpgradeCreateView, UpgradeDetailView, UpgradeDeleteView, UpgradeUpdateView
from . import views
app_name= 'upgrades'
urlpatterns = [
    path('', UpgradeListView.as_view(), name="upgrades-home"),
    path('new/', UpgradeCreateView.as_view(), name="upgrades-create"),
    path('schedule/', views.schedule_upgrade, name='schedule_upgrade'),
    path('<int:pk>/', UpgradeDetailView.as_view(), name='upgrade-detail'),
    path('<int:pk>/update/', UpgradeUpdateView.as_view(), name="upgrade-update"),
    path('<int:pk>/delete/', UpgradeDeleteView.as_view(), name="upgrade-delete")
]

NetNua/upgrades/models.py
import os

from django.db import models
from devices.models import Device

from django.contrib.auth.models import User
from django.conf import settings


class UpgradeEvent(models.Model):
    firmware_files_path = os.path.join(settings.BASE_DIR, 'upgrades', 'firmware_files')
    CODE_VERSION_CHOICES = [(f, f) for f in os.listdir(firmware_files_path)]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    devices = models.ManyToManyField(Device)
    code_version = models.CharField(max_length=100, choices=CODE_VERSION_CHOICES)
    scheduled_upgrade = models.DateTimeField()
    description = models.TextField(blank=True, null=True)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return f"Upgrade Event {self.pk} - {self.scheduled_upgrade}"

NetNua/upgrades/forms.py
import os

from django import forms
from .models import UpgradeEvent


from django.forms.widgets import SelectMultiple, DateTimeInput
from django.conf import settings
def get_code_versions():
    upgrade_dir = os.path.join(settings.BASE_DIR, 'upgrades','firmware_files')
    file_list = [f for f in os.listdir(upgrade_dir) if os.path.isfile(os.path.join(upgrade_dir, f))]
    return [(f, f) for f in file_list]
class UpgradeEventForm(forms.ModelForm):
    code_version=forms.ChoiceField(choices=get_code_versions())
    class Meta:
        model = UpgradeEvent
        fields = ['devices','code_version', 'scheduled_upgrade', 'description']
        exclude = ['user']
        widgets = {
            'devices': SelectMultiple(attrs={'multiple': True, 'class' : 'form-control'}),
            'scheduled_upgrade': forms.widgets.DateTimeInput(attrs={'type': 'datetime-local', 'class' : 'form-control'}),
            'description': forms.Textarea(attrs={'rows': 3, 'cols': 40, 'class' : 'form-control'}),

        }

NetNua/upgrades/views.py
import os
import time
from datetime import datetime

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from netmiko import ConnectHandler, file_transfer, progress_bar

from .forms import UpgradeEventForm
from .models import UpgradeEvent


def home(request):
    upgrades = UpgradeEvent.objects.all()
    return render(request, 'upgrades/home.html', {'upgrades': upgrades})


class UpgradeDetailView(DetailView):
    model = UpgradeEvent


class UpgradeListView(ListView):
    model = UpgradeEvent
    template_name = 'upgrades/home.html'
    context_object_name = 'upgrades'


class UpgradeCreateView(LoginRequiredMixin, CreateView):
    model = UpgradeEvent
    form_class = UpgradeEventForm
    success_url = "/upgrades"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class UpgradeUpdateView(LoginRequiredMixin, UpdateView):
    model = UpgradeEvent
    form_class = UpgradeEventForm
    success_url = "/upgrades"


class UpgradeDeleteView(LoginRequiredMixin, DeleteView):
    model = UpgradeEvent
    success_url = '/upgrades'


@login_required
def schedule_upgrade(request):
    if request.method == 'POST':
        form = UpgradeEventForm(request.POST)
        if form.is_valid():
            upgrade_event = form.save(commit=False)
            upgrade_event.user = request.user
            upgrade_event.save()
            form.save_m2m()  # Save many-to-many relationships
            form = UpgradeEventForm()  # Reset the form
    else:
        form = UpgradeEventForm()

    return render(request, 'upgrades/schedule_upgrade.html', {'form': form})


def check_upgrades(request):
    now = datetime.now()
    upgrades = UpgradeEvent.objects.all().filter(scheduled_upgrade__lte=now, completed=False)
    for upgrade in upgrades:
        if scp_file(upgrade):
            print("All devices have been upgraded. Verifying Connection")
            for device in upgrade.devices.all():
                print(f"Verifying Connection to {device.dnsName}")
                if wait_for_connection(device):
                    print(f"Connection to {device.dnsName} verified")
                    device.currentVersion = upgrade.code_version
                else:
                    print(f"Connection to {device.dnsName} failed")


def scp_file(upgrade):
    for device in upgrade.devices.all():
        if device.manufacturer == 'Arista':
            device_type = 'arista_eos'
            device_location = '/mnt/flash'
        elif device.manufacturer == 'Cisco':
            device_type = 'cisco_ios'
            device_location = 'flash:'
        elif device.manufacturer == 'Juniper':
            device_type = 'juniper_junos'
            device_location = 'var/home/netnua'
        device = {
            "device_type": device_type,
            "ip": device.dnsName,
            "username": device.loginUser,
            "password": device.loginPwd,
            "session_log": "my_session.log",
        }
        source_file = os.path.join(settings.BASE_DIR, 'upgrades', 'firmware_files', upgrade.code_version)
        file_system = device_location
        dest_file = upgrade.code_version
        ssh_conn = ConnectHandler(**device)
        ssh_conn.enable()
        transfer_dict = file_transfer(
            ssh_conn,
            source_file=source_file,
            dest_file=dest_file,
            file_system=file_system,
            direction="put",
            overwrite_file=True,
            progress4=progress_bar,
        )
        print(transfer_dict)
        print(f"Successfully transferred file to {{device}}")
        boot_system_cmd = f"boot system flash:{dest_file}"
        ssh_conn.send_command(boot_system_cmd)
        ssh_conn.send_command("write memory")
        ssh_conn.send_command("copy running-config startup-config")
        ssh_conn.send_command("reload in 5")
        ssh_conn.disconnect()

    return True


def wait_for_connection(device, max_retries=10, retry_interval=30):
    retries = 0
    while retries < max_retries:
        is_connected = verify_device_connection(device)
        if is_connected:
            return True
        else:
            time.sleep(retry_interval)
            retries += 1
    return False


def verify_device_connection(device):
    try:
        connection = ConnectHandler(**device)
        output = connection.send_command("show version")
        connection.disconnect()

        # Check for specific keywords in the output to ensure you are connected to the correct device
        if "Arista" in output:
            return True
        else:
            return False
    except Exception as e:
        print(f"Connection failed: {e}")
        return False

NetNua/upgrades/templates/upgrades/home.html
{% extends "devices/base.html" %}
{% block content %}
  <h2><u>Upgrade Scheduling</u></h2>
  {% if upgrades %}
    <table class ="table table-bordered table-hover">
      <thead>
        <tr>
          <th>ID</th>
          <th>Scheduled Time</th>
          <th>Description</th>
          <th>Devices</th>
          <th>User</th>
          <th>Code Version</th>
          <th>Completed</th>
        </tr>
      </thead>
      <tbody>
        {% for upgrade in upgrades %}
          <tr class = 'clickable-row' onclick="window.location='/upgrades/{{upgrade.pk}}';">
            <td>{{ upgrade.pk }}</td>
            <td>{{ upgrade.scheduled_upgrade }}</td>
            <td>{{ upgrade.description }}</td>
            <td>
              {% for device in upgrade.devices.all %}
                {{ device.dnsName }}{% if not forloop.last %}, {% endif %}
              {% endfor %}
            </td>
            <td>{{upgrade.user}}</td>
            <td>{{upgrade.code_version}}</td>
            <td>{% if upgrade.completed %}
              <span style="color: green;">&#x2714;</span> <!-- Display a checkmark -->
            {% else %}
              <span style="color: red;">&#x2718;</span> <!-- Display a cross -->
            {% endif %}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>No upgrades found.</p>
  {% endif %}
{% endblock content %}
{% block nav_items %}
<a class="nav-item nav-link" href="{% url 'upgrades:upgrades-create' %}">New Upgrade</a>
{% endblock nav_items %}

NetNua/upgrades/templates/upgrades/schedule_upgrade.html
{% extends 'upgrades/home.html' %}

{% block content %}
  <h2>Schedule Upgrade</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.devices.label_tag }}<br>
    {{ form.devices }}<br>
    {{ form.scheduled_upgrade.label_tag }}<br>
    {{ form.scheduled_upgrade }}<br>
    {{ form.description.label_tag }}<br>
    {{ form.description }}<br>
    <button type="submit" class="btn btn-primary">Schedule</button>
  </form>
{% endblock content %}
{% block nav_items %}
<a class="nav-item nav-link" href="{% url 'upgrades:upgrades-create' %}">New Upgrade</a>
{% endblock nav_items %}

NetNua/upgrades/templates/upgrades/upgradeevent_confirm_delete.html
{% extends "devices/base.html" %}
{% block content %}
<div class ="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class = "form-group">
            <legend class="border-bottom mb-4">Delete</legend>
            <h2> Are you sure for deletion?</h2>
        </fieldset>
        <div class ="form-group">
            <button class="btn btn-outline-danger" type="submit">
                Confirm Deletion
            </button>
            <a class="btn btn-outline-secondary" href="{% url 'upgrades:upgrade-detail' object.id %}">
                Cancel
            </a>
        </div>
    </form>


</div>
{% endblock content %}
{% block nav_items %}
<a class="nav-item nav-link" href="{% url 'upgrades:upgrades-create' %}">New Upgrade</a>
{% endblock nav_items %}

NetNua/upgrades/templates/upgrades/upgradeevent_detail.html
{% extends "upgrades/home.html" %}
{% block content %}
    <h1>Scheduled Time: {{ object.scheduled_upgrade }}</h1>
<p> Devices:
{% for device in object.devices.all %}
                {{ device.dnsName }}{% if not forloop.last %}, {% endif %}
              {% endfor %}
</p>
    <p> Description: {{ object.description }}</p>
    <p> User: {{ object.user }}</p>
    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'upgrades:upgrade-update' object.id %}"> Update </a>
    <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'upgrades:upgrade-delete' object.id %}"> Delete </a>
{% endblock content %}
{% block nav_items %}
<a class="nav-item nav-link" href="{% url 'upgrades:upgrades-create' %}">New Upgrade</a>
{% endblock nav_items %}

NetNua/upgrades/templates/upgrades/upgradeevent_form.html
{% extends "devices/base.html" %}

{% block content %}
<div class="content-section">
    <h2>Create Upgrade Event</h2>
    <div class = "form-group"></div>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Create Upgrade Event</button>
    </form>
</div>
</div>
{% endblock content %}
{% block nav_items %}
<a class="nav-item nav-link" href="{% url 'upgrades:upgrades-create' %}">New Upgrade</a>
{% endblock nav_items %}