NetNua/devices/urls.py
from django.urls import path
from .views import DeviceListView, DeviceDetailView, DeviceCreateView, DeviceUpdateView, DeviceDeleteView
from . import views
app_name = 'devices'
urlpatterns = [
    path('', DeviceListView.as_view(), name="devices-home"),
    path('sort/<str:sort_by>/', DeviceListView.as_view(), name="device_home_sorted"),
    path('<int:pk>/', DeviceDetailView.as_view(), name='device-detail'),
    path('new/', DeviceCreateView.as_view(), name="device-create"),
    path('<int:pk>/update/', DeviceUpdateView.as_view(), name="device-update"),
    path('<int:pk>/delete/', DeviceDeleteView.as_view(), name="device-delete")
]

NetNua/logs/urls.py
from django.urls import path
from . import views

app_name = 'logs'

urlpatterns = [
    path('', views.log_list, name='log_list'),
]

NetNua/devices/models.py
from django.db import models
from django.urls import reverse


class Device(models.Model):
    MANUFACTURER_CHOICES = [
        ('Cisco', 'Cisco'),
        ('Juniper', 'Juniper'),
        ('Huawei', 'Huawei'),
        ('Arista', 'Arista'),
    ]
    dnsName = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    loginPwd = models.CharField(max_length=100)
    loginUser = models.CharField(max_length=100)
    deviceType = models.CharField(max_length=100)
    currentVersion = models.CharField(max_length=100)
    manufacturer = models.CharField(max_length=20, choices=MANUFACTURER_CHOICES, default='Cisco')

    def __str__(self):
        return self.dnsName

    def get_absolute_url(self):
        return reverse('device-detail', kwargs={'pk': self.pk})

NetNua/devices/forms.py
from django import forms
from .models import Device


class DeviceForm(forms.ModelForm):
    class Meta:
        model = Device
        fields = ['dnsName','manufacturer','deviceType','location', 'loginUser', 'loginPwd']

NetNua/devices/views.py
import paramiko
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from logs.models import Log
from .forms import DeviceForm
from .models import Device
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)


def home(request):
    context = {
        'devices': Device.objects.all()
    }
    return render(request, 'devices/home.html', context)


class DeviceListView(ListView):
    model = Device
    template_name = 'devices/home.html'
    context_object_name = 'devices'
    def get_queryset(self):
        sort_by = self.kwargs.get('sort_by')
        if sort_by == 'manufacturer':
            return Device.objects.order_by('manufacturer')
        elif sort_by == 'deviceType':
            return Device.objects.order_by('deviceType')
        elif sort_by == 'location':
            return Device.objects.order_by('location')
        elif sort_by == 'currentVersion':
            return Device.objects.order_by('currentVersion')
        else:
            return Device.objects.all()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sort_by'] = self.kwargs.get('sort_by')
        return context

class DeviceDetailView(DetailView):
    model = Device


class DeviceCreateView(LoginRequiredMixin, CreateView):
    model = Device
    form_class = DeviceForm
    success_url = "/"
    def form_valid(self, form):
        form.instance.created_by = self.request.user
        response = super().form_valid(form)
        result = update_device_version(self.object)
        if result == "success":
            messages.success(self.request, "Device created successfully and version information updated.")
        else:
            messages.error(self.request, f"Device created, but failed to update version information: {result}")
        return response


class DeviceUpdateView(LoginRequiredMixin, UpdateView):
    model = Device
    fields = ['dnsName', 'location', 'manufacturer', 'deviceType', 'manufacturer', 'currentVersion', 'loginUser',
              'loginPwd']
    success_url = "/"


class DeviceDeleteView(LoginRequiredMixin, DeleteView):
    model = Device
    success_url = '/'


def update_device_version(device):
    dnsname = device.dnsName
    username = device.loginUser
    password = device.loginPwd
    manufacturer = device.manufacturer

    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    if manufacturer == 'Cisco':
        try:
            ssh.connect(dnsname, username=username, password=password)
            stdin, stdout, stderr = ssh.exec_command("show version")
            output = stdout.readlines()
            output = output[0].split(",")
            version = output[2].replace('Version', '').strip()
            print(version)
            device.currentVersion = version
            device.save()
            create_log_entry(f"Version updated to {version}", "INFO", device)
            return "success"
        except Exception as e:
            create_log_entry(f"Failed to update version: {e}", "ERROR", device)
            return str(e)
    elif manufacturer == 'Arista':
        try:
        # Automatically add SSH keys from servers
            ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        # Connect to the server
            ssh.connect(dnsname, username=username, password=password)
        # Run the command to get the version from the Cisco device
            stdin, stdout, stderr = ssh.exec_command("show version")
        # Get the output from the executed command
            output = stdout.readlines()
            version = output[5].replace('Software image version:', '').strip()
            device.currentVersion = version
            device.save()
            return "success"
        except Exception as e:
            return str(e)
def create_log_entry(message,log_level,device):
    log_entry = Log.objects.create(
        message=message,
        log_type=log_level,
        device=device
    )
    log_entry.save()

NetNua/devices/templates/devices/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'devices/main.css' %}">
    
</head>
<body>
<header class="site-header">
  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
    <div class="container">
      <a class="navbar-brand mr-4" href="/">Net Nua</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="/">Home</a>
            <a class="nav-item nav-link" href="/upgrades">Upgrade Scheduling</a>
            <a class="nav-item nav-link" href="/scripts">Script Management</a>
            <a class="nav-item nav-link" href="/devices">Device Management</a>
          <a class="nav-item nav-link" href="/logs">Logs</a>

        </div>
        <!-- Navbar Right Side -->
        <div class="navbar-nav">
            {% if user.is_authenticated %}
          <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            {% block nav_items %}
            <a class="nav-item nav-link" href="{% url 'devices:device-create' %}">New Device</a>
            {% endblock %}
            {% else %}
          <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
            {% endif %}
        </div>
      </div>
    </div>
  </nav>
</header>
<main role="main" class="container">
  <div class="row">
    <div class="col-md-12">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
      {% block content %}{% endblock %}
    </div>

  </div>
</main>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

NetNua/devices/templates/devices/device_confirm_delete.html
{% extends "devices/base.html" %}
{% block content %}
<div class ="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class = "form-group">
            <legend class="border-bottom mb-4">Delete</legend>
            <h2> Are you sure for deletion?</h2>
        </fieldset>
        <div class ="form-group">
            <button class="btn btn-outline-danger" type="submit">
                Confirm Deletion
            </button>
            <a class="btn btn-outline-secondary" href="{% url 'devices:device-detail' object.id %}">
                Cancel
            </a>
        </div>
    </form>


</div>
{% endblock content %}

NetNua/devices/templates/devices/device_detail.html
{% extends "devices/base.html" %}
{% block content %}
    <p>DnsName: {{ object.dnsName }}</p>
    <p>Manufacturer: {{object.manufacturer}}</p>
    <p>Device Type: {{object.deviceType}}</p>
    <p>Current Version: {{object.currentVersion}}</p>
    <p>Location: {{ object.location }}</p>
    <p></p>
    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'devices:device-update' object.id %}"> Update </a>
    <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'devices:device-delete' object.id %}"> Delete </a>
{% endblock content %}

NetNua/devices/templates/devices/device_form.html
{% extends "devices/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class ="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class = "form-group">
            <legend class="border-bottom mb-4">New Device</legend>
            {{ form|crispy }}

        </fieldset>
        <div class ="form-group">
            <button class="btn btn-outline-info" type="submit">
                Create
            </button>
        </div>
    </form>


</div>
{% endblock content %}

NetNua/devices/templates/devices/home.html
{% extends "devices/base.html" %}
{% block content %}
  <h2><u>Device Management</u></h2>
  {% if devices %}
    <table class ="table table-bordered table-hover">
      <thead>
        <tr>
          <th class = 'clickable-row' onclick="window.location='/devices/sort/pk';">ID</th>
          <th class = 'clickable-row' onclick="window.location='/devices/sort/dnsName';">DNS Name</th>
          <th class = 'clickable-row' onclick="window.location='/devices/sort/location';">Location</th>
          <th class = 'clickable-row' onclick="window.location='/devices/sort/manufacturer';">Manufacturer</th>
          <th class = 'clickable-row' onclick="window.location='/devices/sort/deviceType';">Device Type</th>
          <th class = 'clickable-row' onclick="window.location='/devices/sort/currentVersion';">Current Version</th>
        </tr>
      </thead>
      <tbody>
        {% for device in devices %}
          <tr class = 'clickable-row' onclick="window.location='/devices/{{device.pk}}';">
            <td>{{ device.pk }}</td>
            <td>{{ device.dnsName }}</td>
            <td>{{ device.location }}</td>
            <td>{{ device.manufacturer }}</td>
            <td>{{ device.deviceType }}</td>
            <td>{{ device.currentVersion }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>No devices found.</p>
  {% endif %}
{% endblock content %}